spring:
  datasource:
    url: jdbc:postgresql://5.35.104.138:9725/fintech
    username: beta_sdf
    password: zMpkRXGZvGbJXBhqusQdWA7LWHXez4iPDqnzcU7uVSe
    hikari:
      schema: zhiger
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    org.telegram: debug
    root: info

bot:
  token: 8392819757:AAHEqiK5rRJ45EyXGfm-fOc3CLs501cxlEY
  username: mangilik_el_jastary_bot
