spring:
  datasource:
    url: jdbc:postgresql://104.248.39.82:5432/mangilikeldb
    username: bot_user
    password: bot_password
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        bytecode:
          provider: bytebuddy   # ← ВОТ ОНО, ГЛАВНОЕ

logging:
  level:
    org.telegram: debug
    root: info

bot:
  enabled: true
  token: 8584001024:AAG_nL0hK4LYTUZdrVAUeqdH604boqmk5CM
  username: mangilik_el_jastary_mektep_bot
