spring:
  datasource:
    url: jdbc:postgresql://104.248.39.82:5432/mangilikel
    username: mangilikel
    password: mangilikel
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        bytecode:
          provider: bytebuddy   # ← ВОТ ОНО, ГЛАВНОЕ
